CREATE TABLE USERS(
	USERID VARCHAR2(50) PRIMARY KEY,
	USERPW VARCHAR2(50) NOT NULL,
	USERNAME VARCHAR2(100) NOT NULL,
	USERBIRTH DATE NOT NULL,
	USERPHONE VARCHAR2(100) NOT NULL,
	USERADDR VARCHAR2(300) NOT NULL,
	USEREMAIL VARCHAR2(200) NOT NULL
);


SELECT * FROM USERS;
DROP TABLE cart;
CREATE TABLE CART(
	CARTNUM NUMBER (10) PRIMARY KEY,
	USERID VARCHAR2(50) NOT NULL,
	title VARCHAR2(300) NOT NULL,
	discount NUMBER (10) NOT NULL,
	image VARCHAR2(500) NOT NULL,
	isbn varchar2(500) NOT NULL,
	COUNT NUMBER (10) NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

SELECT * FROM CART;
DROP TABLE ORDERLIST ;
CREATE TABLE ORDERLIST(
	ORDERNUM NUMBER (10) PRIMARY KEY,
	USERID VARCHAR2(50) NOT NULL,
	title VARCHAR2(300) NOT NULL,
	image VARCHAR2(500) NOT NULL,
	author VARCHAR2(150),
	discount NUMBER(10),
	publisher VARCHAR2(150),
	pubdate DATE,
	DELIVERY_STATUS VARCHAR2(100) NOT NULL,
	isbn varchar2(500) NOT NULL,
	COUNT NUMBER(10) NOT NULL,
	CATEGORY VARCHAR2(150) NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

SELECT * FROM ORDERLIST;

CREATE SEQUENCE order_seq
START WITH 1
INCREMENT BY 1;

/* INSERT INTO ORDERLIST VALUES (order_seq.nextval, USERID, title, title, author, discount, publisher, pubdate, DELIVERY_STATUS, COUNT, CATEGORY ); */

CREATE TABLE QNA(
	QNANUM NUMBER (10) PRIMARY KEY,
	USERID VARCHAR2(50) NOT NULL,
	QNADETAILS VARCHAR2(3000) NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);